""
"" Janus setup
""

" Define pathes
let g:janus_path = fnamemodify(resolve(expand("<sfile>:p")), ":h")
let g:janus_vim_path = fnamemodify(resolve(expand("<sfile>:p" . "vim")), ":h")

" Source janus's core
exe 'source ' . g:janus_vim_path . '/core/pathogen/autoload/pathogen.vim'
exe 'source ' . g:janus_vim_path . '/core/before/plugin/janus.vim'

""
"" Customisations
""

if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

""
"" Pathogen Setup
""

" You should note that groups will be processed by Pathogen in reverse
" order they were added.
call janus#add_group("tools")
call janus#add_group("langs")
call janus#add_group("colors")
call janus#add_group("custom")
call janus#add_group("core")

call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

""
"" Customizations
""

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
